### ISSUE TITLE
Scaffolding

### ISSUE THREAD

**Issue by neftalyluis** [TachibanaLabs/imgbrd#1]
@Merak1 Lo que el nombre dice, agregale los clasicos index.[html, js, css] y agregale el Firebase

Aca la [documentación](https://firebase.google.com/docs/web/setup)

Si tienes dudas, ya te la sabritas.

**Comment by Merak1** [comment]
brocas , en eso estoy.
Me imagino que igual se le pueden meter otros frameworks como el bustra o fundation  y demás cosas no?

**Comment by neftalyluis** [comment]
Si, eso es lo planeado, pero primero necesito que aprendas a jugar con el
Firebase, está cagado, solo integrarlo y crea los primeros archivos, lo
demás yo te lo dejo en tareitas más adelante

**Comment by Merak1** [comment]
roger roger

**Comment by Merak1** [comment]
Ya, revisame please .
No puede ser que tardara tanto

**Comment by neftalyluis** [comment]
No importa que tanto tardes, hazme el PR dirigido a este Repo para poder comentarte tus cambios

**Comment by neftalyluis** [comment]
Ya están mis comentarios en #2, resuelvelos pls

**Comment by neftalyluis** [comment]
Closing #2
