### ISSUE TITLE
Aprender a hacerle push a datos a la DB de Firebase

### ISSUE THREAD

**Issue by neftalyluis** [TachibanaLabs/imgbrd#3]
Ahora que tenemos todo listo seria buena idea darte un requerimiento para comenzar

Una buena idea sería hacer una mini app de mensajes y este consiste de:

- Que con un input y un botón puedas enviar mensajes en la DB de Firebase
- Que exista un div donde se vean todos los mensajes que están en la misma DB

Checa estos links 

https://firebase.google.com/docs/database/web/structure-data
https://firebase.google.com/docs/database/web/save-data
https://firebase.google.com/docs/database/web/retrieve-data

**Comment by neftalyluis** [comment]
No es necesario que le des un diseño a este requerimiento pero sería un buen agregado

**Comment by Merak1** [comment]
![ok](https://user-images.githubusercontent.com/19805451/35586154-a5329a34-05bf-11e8-95c7-b2dfe2dbeef5.jpg)

**Comment by Merak1** [comment]
ᕙ(⇀‸↼‶)ᕗ

**Comment by neftalyluis** [comment]
Cerrando, solucionado en #4
