### ISSUE TITLE
Replicar un Board de Imageboard

### ISSUE THREAD

**Issue by neftalyluis** [TachibanaLabs/imgbrd#5]
Ahora que ya sabes como funciona a muy grandes rasgos la DB de Firebase este es el momento donde debes de crear un Board Funcional (solo texto por ahora)

Replica el template y estilo del imgboard que más te guste, y haz que tenga esa lógica de Hilos y respuestas, trata de por ahora no meter funcionalidad compleja, esa la podemos dejar para después

Cualquier duda que tengas trata de ponerla en este Issue, hay que mantener limpio el Chat para que Juanito no esté jodiendo 

 ᕕ( ⌓̈ )ᕗ

**Comment by neftalyluis** [comment]
Mandame screenshots de tu avance pls

**Comment by Merak1** [comment]
Sorry, me quedé haciendolo y no he subido nada

**Comment by Merak1** [comment]
![image](https://user-images.githubusercontent.com/19805451/36006279-971420aa-0d01-11e8-81e5-251e3c39cf0f.png)

**Comment by Merak1** [comment]
![image](https://user-images.githubusercontent.com/19805451/36006297-a9e6bd96-0d01-11e8-953e-24bab4a73965.png)

**Comment by Merak1** [comment]
Estoy con lo que quede vacio el text area y el input sin que joda el evento de firebase

**Comment by neftalyluis** [comment]
Mandame un PR, porfa

**Comment by neftalyluis** [comment]
Se aplico en #6 , cierro
